from datetime import datetime

from fastapi import HTTPException, status

from app.database import expenses
from app.models import Expense, ExpenseResponse


"""
Expense Service

This module contains all the business logic related to expense management.

Responsibilities:
- Create expenses
- Retrieve expenses
- Search expenses by ID

Routes should call these functions instead of implementing
business logic themselves.
"""

def _find_expense_index_helper(expense_id: int) -> int:

    """

    Find the index of an expense by its unique ID.

    Args:

        expense_id: Unique identifier of the expense.

    Returns:

        int: Index of the matching expense in the list.

    Raises:

        HTTPException: If the expense does not exist.

    """

    for index, expense in enumerate(expenses):

        if expense.id == expense_id:

            return index

    raise HTTPException(

        status_code=status.HTTP_404_NOT_FOUND,

        detail="Expense not found",

    )

def create_expense_service(expense: Expense) -> ExpenseResponse:
    """
    Create a new expense.

    A unique ID and creation timestamp are generated by the server.
    The newly created expense is stored in the application's data store.

    Args:
        expense: Expense data received from the client.

    Returns:
        ExpenseResponse: The newly created expense.
    """

    new_expense = ExpenseResponse(
        id=len(expenses) + 1,
        amount=expense.amount,
        category=expense.category,
        description=expense.description,
        created_at=datetime.now(),
    )

    # Persist the expense in our temporary in-memory storage.
    expenses.append(new_expense)

    return new_expense

def get_all_expenses_service() -> list[ExpenseResponse]:
    """
    Retrieve all stored expenses.

    Returns:
        list[ExpenseResponse]: List of all expenses.
    """

    return expenses

def get_expense_by_id_service(expense_id: int) -> ExpenseResponse:
    """
    Retrieve a single expense by its unique ID.

    Args:
        expense_id: Unique identifier of the expense.

    Returns:
        ExpenseResponse: Matching expense.

    Raises:
        HTTPException: If the expense does not exist.
    """


    index = _find_expense_index_helper(expense_id)
    return expenses[index]

    

def update_expense_by_id_service(expense_id: int, updated_expense: Expense) -> ExpenseResponse:
    """
    Update an existing expense by its unique ID.

    Args:
        expense_id: Unique identifier of the expense to be updated.
        updated_expense: New data for the expense.

    Returns:
        ExpenseResponse: The updated expense.

    Raises:
        HTTPException: If the expense does not exist.
    """

    index = _find_expense_index_helper(expense_id)

    existing_expense = expenses[index]

    updated = ExpenseResponse(

        id=existing_expense.id,

        amount=updated_expense.amount,

        category=updated_expense.category,

        description=updated_expense.description,

        created_at=existing_expense.created_at,

    )

    expenses[index] = updated
    return updated

    
def delete_expense_by_id_service(expense_id: int) -> None:
    """
    Delete an existing expense by its unique ID.

    Args:
        expense_id: Unique identifier of the expense to be deleted.

    Raises:
        HTTPException: If the expense does not exist.
    """

    index = _find_expense_index_helper(expense_id)

    deleted_expense = expenses.pop(index)
    return deleted_expense
   

def filter_expenses_by_category_service(category: str) -> list[ExpenseResponse]:
    """
    Filter expenses based on their category.

    Args:
        category: The category to filter expenses by.

    Returns:
        list[ExpenseResponse]: List of expenses that match the specified category.
    """

    filtered_expenses = [expense for expense in expenses if expense.category == category]
    return filtered_expenses


def get_expenses_by_min_price_service(min_price: float) -> list[ExpenseResponse]:
    """
    Filter expenses based on a minimum price.

    Args:
        min_price: The minimum price to filter expenses by.

    Returns:
        list[ExpenseResponse]: List of expenses that have an amount greater than or equal to the specified minimum price.
    """

    filtered_expenses = [expense for expense in expenses if expense.amount >= min_price]
    return filtered_expenses