from datetime import datetime

from fastapi import HTTPException, status

from app.database import expenses
from app.models import Expense, ExpenseResponse


"""
Expense Service

This module contains all the business logic related to expense management.

Responsibilities:
- Create expenses
- Retrieve expenses
- Search expenses by ID

Routes should call these functions instead of implementing
business logic themselves.
"""


def create_expense(expense: Expense) -> ExpenseResponse:
    """
    Create a new expense.

    A unique ID and creation timestamp are generated by the server.
    The newly created expense is stored in the application's data store.

    Args:
        expense: Expense data received from the client.

    Returns:
        ExpenseResponse: The newly created expense.
    """

    new_expense = ExpenseResponse(
        id=len(expenses) + 1,
        amount=expense.amount,
        category=expense.category,
        description=expense.description,
        created_at=datetime.now(),
    )

    # Persist the expense in our temporary in-memory storage.
    expenses.append(new_expense)

    return new_expense


def get_all_expenses() -> list[ExpenseResponse]:
    """
    Retrieve all stored expenses.

    Returns:
        list[ExpenseResponse]: List of all expenses.
    """

    return expenses


def get_expense_by_id(expense_id: int) -> ExpenseResponse:
    """
    Retrieve a single expense by its unique ID.

    Args:
        expense_id: Unique identifier of the expense.

    Returns:
        ExpenseResponse: Matching expense.

    Raises:
        HTTPException: If the expense does not exist.
    """

    for expense in expenses:
        if expense.id == expense_id:
            return expense

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Expense not found",
    )